services:
  - type: web
    name: callu
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: NEXT_PUBLIC_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
